//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/WeaponControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @WeaponControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @WeaponControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WeaponControlls"",
    ""maps"": [
        {
            ""name"": ""GamePlay"",
            ""id"": ""647d09bb-a459-4147-8f33-7211113d45f1"",
            ""actions"": [
                {
                    ""name"": ""Action_00"",
                    ""type"": ""Button"",
                    ""id"": ""cc537eac-7d36-48eb-8669-134003e98a44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_01"",
                    ""type"": ""Button"",
                    ""id"": ""e2b0381f-6ddb-43bc-bf88-cc7f9e9caa22"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_02"",
                    ""type"": ""Button"",
                    ""id"": ""def2af84-5bdd-4eea-89ce-f32966173682"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_03"",
                    ""type"": ""Button"",
                    ""id"": ""01945739-c5b8-4b33-b9bf-6eba94fcac5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_04"",
                    ""type"": ""Button"",
                    ""id"": ""535b5d13-0a3a-4897-a82f-052e4b1cf69f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_05"",
                    ""type"": ""Button"",
                    ""id"": ""0eb4a351-9e76-4f18-bf25-baf4621b3076"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_06"",
                    ""type"": ""Button"",
                    ""id"": ""28f9caaf-09ca-4938-814d-3ea9118f318a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Button"",
                    ""id"": ""08722c17-b650-49e8-be2f-03244b812b40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""06618061-ff4f-4328-807b-dbb9ba55faa1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cbcbd835-15ea-4184-9c73-b318b6248704"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_00"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54151138-c0b5-4f02-8376-6b64a20298e4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7415e3ac-65c7-4f79-8d67-93e4ee1947d3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b07cf5e-39be-47a2-8799-5f5cebc7d24a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62e4ab25-4463-4cf4-97dd-c9e721c2e968"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0418b96d-5dcf-457a-8363-700e6eab7688"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_05"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c9c6760-0cc6-40af-8ff4-f72a7354c95d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_06"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99a90c5b-3db8-416e-90fc-f78a61c7173f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67dd32c9-1f28-4a40-ae5e-89aeb6711ceb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamePlay
        m_GamePlay = asset.FindActionMap("GamePlay", throwIfNotFound: true);
        m_GamePlay_Action_00 = m_GamePlay.FindAction("Action_00", throwIfNotFound: true);
        m_GamePlay_Action_01 = m_GamePlay.FindAction("Action_01", throwIfNotFound: true);
        m_GamePlay_Action_02 = m_GamePlay.FindAction("Action_02", throwIfNotFound: true);
        m_GamePlay_Action_03 = m_GamePlay.FindAction("Action_03", throwIfNotFound: true);
        m_GamePlay_Action_04 = m_GamePlay.FindAction("Action_04", throwIfNotFound: true);
        m_GamePlay_Action_05 = m_GamePlay.FindAction("Action_05", throwIfNotFound: true);
        m_GamePlay_Action_06 = m_GamePlay.FindAction("Action_06", throwIfNotFound: true);
        m_GamePlay_Look = m_GamePlay.FindAction("Look", throwIfNotFound: true);
        m_GamePlay_Move = m_GamePlay.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamePlay
    private readonly InputActionMap m_GamePlay;
    private IGamePlayActions m_GamePlayActionsCallbackInterface;
    private readonly InputAction m_GamePlay_Action_00;
    private readonly InputAction m_GamePlay_Action_01;
    private readonly InputAction m_GamePlay_Action_02;
    private readonly InputAction m_GamePlay_Action_03;
    private readonly InputAction m_GamePlay_Action_04;
    private readonly InputAction m_GamePlay_Action_05;
    private readonly InputAction m_GamePlay_Action_06;
    private readonly InputAction m_GamePlay_Look;
    private readonly InputAction m_GamePlay_Move;
    public struct GamePlayActions
    {
        private @WeaponControlls m_Wrapper;
        public GamePlayActions(@WeaponControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action_00 => m_Wrapper.m_GamePlay_Action_00;
        public InputAction @Action_01 => m_Wrapper.m_GamePlay_Action_01;
        public InputAction @Action_02 => m_Wrapper.m_GamePlay_Action_02;
        public InputAction @Action_03 => m_Wrapper.m_GamePlay_Action_03;
        public InputAction @Action_04 => m_Wrapper.m_GamePlay_Action_04;
        public InputAction @Action_05 => m_Wrapper.m_GamePlay_Action_05;
        public InputAction @Action_06 => m_Wrapper.m_GamePlay_Action_06;
        public InputAction @Look => m_Wrapper.m_GamePlay_Look;
        public InputAction @Move => m_Wrapper.m_GamePlay_Move;
        public InputActionMap Get() { return m_Wrapper.m_GamePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamePlayActions set) { return set.Get(); }
        public void SetCallbacks(IGamePlayActions instance)
        {
            if (m_Wrapper.m_GamePlayActionsCallbackInterface != null)
            {
                @Action_00.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_00;
                @Action_00.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_00;
                @Action_00.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_00;
                @Action_01.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_01;
                @Action_01.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_01;
                @Action_01.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_01;
                @Action_02.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_02;
                @Action_02.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_02;
                @Action_02.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_02;
                @Action_03.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_03;
                @Action_03.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_03;
                @Action_03.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_03;
                @Action_04.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_04;
                @Action_04.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_04;
                @Action_04.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_04;
                @Action_05.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_05;
                @Action_05.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_05;
                @Action_05.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_05;
                @Action_06.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_06;
                @Action_06.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_06;
                @Action_06.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnAction_06;
                @Look.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnLook;
                @Move.started -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GamePlayActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_GamePlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Action_00.started += instance.OnAction_00;
                @Action_00.performed += instance.OnAction_00;
                @Action_00.canceled += instance.OnAction_00;
                @Action_01.started += instance.OnAction_01;
                @Action_01.performed += instance.OnAction_01;
                @Action_01.canceled += instance.OnAction_01;
                @Action_02.started += instance.OnAction_02;
                @Action_02.performed += instance.OnAction_02;
                @Action_02.canceled += instance.OnAction_02;
                @Action_03.started += instance.OnAction_03;
                @Action_03.performed += instance.OnAction_03;
                @Action_03.canceled += instance.OnAction_03;
                @Action_04.started += instance.OnAction_04;
                @Action_04.performed += instance.OnAction_04;
                @Action_04.canceled += instance.OnAction_04;
                @Action_05.started += instance.OnAction_05;
                @Action_05.performed += instance.OnAction_05;
                @Action_05.canceled += instance.OnAction_05;
                @Action_06.started += instance.OnAction_06;
                @Action_06.performed += instance.OnAction_06;
                @Action_06.canceled += instance.OnAction_06;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public GamePlayActions @GamePlay => new GamePlayActions(this);
    public interface IGamePlayActions
    {
        void OnAction_00(InputAction.CallbackContext context);
        void OnAction_01(InputAction.CallbackContext context);
        void OnAction_02(InputAction.CallbackContext context);
        void OnAction_03(InputAction.CallbackContext context);
        void OnAction_04(InputAction.CallbackContext context);
        void OnAction_05(InputAction.CallbackContext context);
        void OnAction_06(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
